<header>
    <a href="index.php">Home</a>
    <a href="product.php">product</a>
    <a href="enquire.php">enquire</a>
    <a href="about.php">about</a>
    <a href="enhancements.php">enhancements</a>
    <a href="manager.php">manager</a>
  </header>
  <img src="images/logo.png" alt="dmc logo" class="logo">
  <nav class="banner">
    <img src="styles/images/bannerCoverImages/BookShelf(Opt).jpg" alt="bookshelf filled with books" class="first">
    <img src="styles/images/bannerCoverImages/BookShelf3(Opt).jpg" alt="bookshelf filled with books" class="second">
  </nav>